### PR TITLE
fix: delete post and broadcast

### PR DESCRIPTION
**Pull request by pastleo**
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-dom-patching-and-temporary-assigns

### CODE REVIEW

**Review by dannyh79 — APPROVED** [review]
Much appreciate the help 🙏

**Comment by taiansu** [comment]
But this will make "create" behavior incorrect. The post list in another screen will be replace, only the newest post shows on screen.

**Comment by dannyh79** [comment]
> But this will make "create" behavior incorrect. The post list in another screen will be replace, only the newest post shows on screen.

Render after updating posts in timeline is also incorrect. 😢 

Issue logged in #3.

**Comment by taiansu** [comment]
截圖 2020-05-21 01 49 37

**Pull request merged**
